# Generated by Django 4.2.1 on 2023-05-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ganapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input_image", models.ImageField(upload_to="input_images/")),
                ("output_image", models.ImageField(upload_to="output_images/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
